import { visibleArticles } from './article-catalogue';

export interface SourceNote { title: string; by: string; summary: string; reviewedAt?: string }

const notes: Record<string, SourceNote> = {
  'https://www.cl.cam.ac.uk/~pr10/iui/licklider60.pdf': { reviewedAt: '2026-10-01', title: 'Man–Computer Symbiosis', by: 'J.C.R. Licklider · 1960 · §3.1', summary: 'Describes preparation that took far longer than interpreting its result. This is a personal observation, not a current workforce benchmark.' },
  'https://www.ece.uvic.ca/~aalbu/CENG%20412%202009/bewley83.pdf': { reviewedAt: '2026-10-01', title: 'Human Factors Testing in the Design of Xerox Star', by: 'Bewley and colleagues · CHI 1983', summary: 'Documents familiar objects, recognition rather than recall, and user testing. It does not establish that graphical interfaces are best for every task.' },
  'https://dougengelbart.org/pubs/augment-3906-Framework.html': { reviewedAt: '2026-10-01', title: 'Augmenting Human Intellect', by: 'Douglas Engelbart · 1962', summary: 'Sets out an ambition to increase human capacity for understanding and solving difficult problems. A research vision, not evidence for our present prototypes.' },
  'https://webaim.org/projects/million/': { reviewedAt: '2026-10-01', title: 'The WebAIM Million', by: 'WebAIM · February 2026 sample', summary: 'Detected WCAG failures on 95.9% of one million home pages. Automated testing finds only some barriers; an error-free scan does not establish accessibility.' },
  'https://www.w3.org/TR/WCAG22/#cc3': { reviewedAt: '2026-10-01', title: 'WCAG 2.2: Complete processes', by: 'W3C · Conformance requirement 3', summary: 'Conformance for a sequence that accomplishes an activity covers all its pages. Access to an isolated control is not the entire question.' },
  'https://www.w3.org/TR/naur/': { reviewedAt: '2026-10-01', title: 'Natural Language Interface Accessibility User Requirements', by: 'W3C · Group Draft Note · September 2022', summary: 'Discusses input and output choices, understanding and error recovery. This is work in progress, not an endorsed conformance standard.' },
  'https://webmachinelearning.github.io/webmcp/': { reviewedAt: '2026-10-01', title: 'WebMCP', by: 'Draft Community Group Report · 30 September 2026', summary: 'Defines structured actions exposed by web pages for compatible agents. Browser support needs separate verification. It does not establish that an app is accessible.' },
  'https://developer.chrome.com/blog/webmcp-epp': { reviewedAt: '2026-10-01', title: 'WebMCP early preview', by: 'Chrome for Developers · February 2026', summary: 'Introduces form-based and JavaScript-based actions. This announcement is not a current browser compatibility matrix.' },
  'https://developer.chrome.com/docs/ai/webmcp': { reviewedAt: '2026-10-05', title: 'WebMCP', by: 'Chrome for Developers · guide updated 1 October 2026', summary: 'Documents an origin trial from Chrome 149 and a local development flag. A route to testing, not support in every browser and agent.' },
  'https://github.com/webmachinelearning/webmcp/blob/6891d0e857a0b35d8478aa8a01958565fb5466cd/continuations-explainer.md': { reviewedAt: '2026-10-05', title: 'WebMCP continuations explainer', by: 'Web Machine Learning Community Group · merged 2 October 2026', summary: 'Proposes continuing a tool call across pages or frames on the same origin, with single-use, revocable tokens. A proposal, not a browser implementation.' },
  'https://modelcontextprotocol.io/docs/2026-07-28/learn/architecture': { reviewedAt: '2026-10-01', title: 'MCP architecture', by: 'Model Context Protocol · version 2026-07-28', summary: 'Explains hosts, clients, servers and tool discovery and invocation. Our spoken, cross-app release-note example is a proposed application of these mechanisms.' },
  'https://github.com/hyperdrift-io/uk-ai-radar/blob/main/WEBMCP.md': { reviewedAt: '2026-10-01', title: 'WebMCP in UK AI Radar', by: 'Hyperdrift · implementation notes', summary: 'Describes tools that operate the same workspace as the page controls. This is our own implementation account, not independent validation.' },
  'https://github.com/hyperdrift-io/bridge-voice': { reviewedAt: '2026-10-01', title: 'First Officer / Bridge Voice', by: 'Hyperdrift · public repository', summary: 'Contains the voice integration and Cargo sandbox recovery path. The current runtime does not go through Traction's MCP tools.' },
  'https://hyperdrift.io/blog/the-agent-is-the-session': { reviewedAt: '2026-10-01', title: 'The Agent Is the Session', by: 'Yann VR · Hyperdrift · August 2026', summary: 'The original Radar account. The Orchestra adaptation narrows its claims about accounts and context: information passed to a page tool crosses into the page.' },
};

export function articleSourceNote(url: string): SourceNote | undefined { if (notes[url]) return notes[url];
  const article = url.startsWith('/articles/') && visibleArticles().find((item) => `/articles/${item.slug}` === url);
  return article ? { title: article.title, by: article.publishedAt ? 'Orchestra · related article' : 'Orchestra · editorial preview', summary: article.excerpt } : undefined; }
